#!/bin/sh
upstream=$1
: ${upstream:=origin}
npm i
#git pull $upstream master || exit -1
git fetch $upstream
git branch -f gh-pages $upstream/gh-pages
rm -rf _public
echo git-`git describe --always` > app/assets/build_id.txt
git clone -s . -b gh-pages _public
./node_modules/.bin/brunch build
cd _public
git add -A . && git commit -a -m 'regen' && git push origin gh-pages
cd ..
git co app/assets/build_id.txt
git push -f $upstream gh-pages
