#!/bin/sh
set -e -x
upstream=$1
: ${upstream:=origin}
: ${REPO:=git@github.com:g0v/g0v.tw}
git fetch $upstream
if [ `git rev-list HEAD...$upstream/master --count` -ne 0 ]; then
  echo "not deploying"
  exit 1
fi
npm i
rm -rf _public
# XXX: use --reference when not in shallow clone
#git clone $REPO --reference . -b gh-pages _public
git clone $REPO -b gh-pages _public

REV=`git describe --always`
BUILD=git-$REV ./node_modules/.bin/brunch b -o
cd _public
git add -A .
git commit-tree -m "regen for $REV" -p `git rev-parse HEAD` -p $REV `git write-tree` | xargs git reset --hard
git push origin gh-pages
cd ..
